#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2026 Petr Wozniak (WOZIWRT project)
#
# Witness for the nights after 2026-08-20. See /usr/sbin/easymesh-nightwatch.
START=99
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/easymesh-nightwatch 60
	procd_set_param respawn 3600 10 0
	procd_set_param stderr 1
	procd_close_instance
}
