#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2026 Petr Wozniak (WOZIWRT project)
#
# Keeps the daemon logs in /tmp in check. See /usr/sbin/easymesh-logcap.
START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/easymesh-logcap
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}
