#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Petr Wozniak <petr.wozniak@gmail.com>

START=95
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /root/mlo-steerd.sh
    procd_set_param respawn 30 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
